// generated by akucc
// built-in type names
#include <stdint.h>
typedef int8_t int8;
typedef int16_t int16;
typedef int32_t int32;
typedef int64_t int64;
typedef uint8_t uint8;
typedef uint16_t uint16;
typedef uint32_t uint32;
typedef uint64_t uint64;
typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned long ulong;
typedef char **stringp;
typedef void *voidp;
#define true 1
#define false 0
#define nil (voidp)0
#define forced (voidp)0

// stdlib headers


// user headers

#include "io.h"



int main(){
println("cum?");
return 0;
}


