var searchData=
[
  ['kernel_5fmain_631',['kernel_main',['../main_8c.html#a0921636b1737a4511853965f143ad1b3',1,'main.c']]],
  ['kill_632',['kill',['../libc_2include_2signal_8h.html#a4539db972bcf3dd8c8b429af0dc3789d',1,'autogenerated_syscalls.c']]]
];
