.TH "acpi_rsdp" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acpi_rsdp
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBsignature\fP [8]"
.br
.ti -1c
.RI "unsigned char \fBchecksum\fP"
.br
.ti -1c
.RI "char \fBoem_id\fP [6]"
.br
.ti -1c
.RI "unsigned char \fBrevision\fP"
.br
.ti -1c
.RI "uint32_t \fBrsdt_address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file acpi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
