.TH "instruction_t" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
instruction_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned short \fBoperator\fP"
.br
.ti -1c
.RI "unsigned short \fBoperand\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file bf2\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
