.TH "interrupt_frame" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interrupt_frame
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBds\fP"
.br
.ti -1c
.RI "uint64_t \fBr15\fP"
.br
.ti -1c
.RI "uint64_t \fBr14\fP"
.br
.ti -1c
.RI "uint64_t \fBr13\fP"
.br
.ti -1c
.RI "uint64_t \fBr12\fP"
.br
.ti -1c
.RI "uint64_t \fBr11\fP"
.br
.ti -1c
.RI "uint64_t \fBr10\fP"
.br
.ti -1c
.RI "uint64_t \fBr9\fP"
.br
.ti -1c
.RI "uint64_t \fBr8\fP"
.br
.ti -1c
.RI "uint64_t \fBbp\fP"
.br
.ti -1c
.RI "uint64_t \fBrdi\fP"
.br
.ti -1c
.RI "uint64_t \fBrsi\fP"
.br
.ti -1c
.RI "uint64_t \fBrdx\fP"
.br
.ti -1c
.RI "uint64_t \fBrbx\fP"
.br
.ti -1c
.RI "uint64_t \fBrcx\fP"
.br
.ti -1c
.RI "uint64_t \fBrax\fP"
.br
.ti -1c
.RI "uint64_t \fBinterrupt_number\fP"
.br
.ti -1c
.RI "uint64_t \fBerror_code\fP"
.br
.ti -1c
.RI "uint64_t \fBip\fP"
.br
.ti -1c
.RI "uint64_t \fBcs\fP"
.br
.ti -1c
.RI "uint64_t \fBflags\fP"
.br
.ti -1c
.RI "uint64_t \fBuser_sp\fP"
.br
.ti -1c
.RI "uint64_t \fBss\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file cpu\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
