.TH "madt" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
madt
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBacpi_header\fP \fBheader\fP"
.br
.ti -1c
.RI "uint32_t \fBlapic_address\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "\fBacpi_madt_entry\fP \fBentries\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 101 of file acpi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
