.TH "mm_region" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mm_region
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uintptr_t \fBbase\fP"
.br
.ti -1c
.RI "uintptr_t \fBtop\fP"
.br
.ti -1c
.RI "enum mm_flags \fBflags\fP"
.br
.ti -1c
.RI "struct \fBfile\fP * \fBfile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file thread\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
