.TH "modinfo" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modinfo
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int(* \fBinit\fP )(struct \fBmod\fP *)"
.br
.ti -1c
.RI "void(* \fBfini\fP )(struct \fBmod\fP *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file mod\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
