.TH "multiboot_tag_framebuffer" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_framebuffer
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmultiboot_tag_framebuffer_common\fP \fBcommon\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      uint16_t \fBframebuffer_palette_num_colors\fP"
.br
.ti -1c
.RI "      \fBmultiboot_color\fP \fBframebuffer_palette\fP [1]"
.br
.ti -1c
.RI "   } "
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      uint8_t \fBframebuffer_red_field_position\fP"
.br
.ti -1c
.RI "      uint8_t \fBframebuffer_red_mask_size\fP"
.br
.ti -1c
.RI "      uint8_t \fBframebuffer_green_field_position\fP"
.br
.ti -1c
.RI "      uint8_t \fBframebuffer_green_mask_size\fP"
.br
.ti -1c
.RI "      uint8_t \fBframebuffer_blue_field_position\fP"
.br
.ti -1c
.RI "      uint8_t \fBframebuffer_blue_mask_size\fP"
.br
.ti -1c
.RI "   } "
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 272 of file multiboot2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
