.TH "multiboot_header" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_header
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBmagic\fP"
.br
.ti -1c
.RI "uint32_t \fBarchitecture\fP"
.br
.ti -1c
.RI "uint32_t \fBheader_length\fP"
.br
.ti -1c
.RI "uint32_t \fBchecksum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 98 of file multiboot2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
