.TH "multiboot_tag_elf_sections" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_elf_sections
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "uint32_t \fBnum\fP"
.br
.ti -1c
.RI "uint32_t \fBentsize\fP"
.br
.ti -1c
.RI "uint32_t \fBshndx\fP"
.br
.ti -1c
.RI "char \fBsections\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 291 of file multiboot2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
