.TH "process" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
process
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pid_t \fBpid\fP"
.br
.ti -1c
.RI "pid_t \fBpgid\fP"
.br
.ti -1c
.RI "char \fBcomm\fP [COMM_SIZE]"
.br
.ti -1c
.RI "unsigned int \fBmagic\fP"
.br
.ti -1c
.RI "phys_addr_t \fBvm_root\fP"
.br
.ti -1c
.RI "int \fBuid\fP"
.br
.ti -1c
.RI "int \fBgid\fP"
.br
.ti -1c
.RI "int \fBexit_intention\fP"
.br
.ti -1c
.RI "int \fBexit_status\fP"
.br
.ti -1c
.RI "struct \fBprocess\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fBdmgr\fP \fBfds\fP"
.br
.ti -1c
.RI "\fBlist\fP \fBchildren\fP"
.br
.ti -1c
.RI "\fBlist\fP \fBthreads\fP"
.br
.ti -1c
.RI "\fBlist_n\fP \fBsiblings\fP"
.br
.ti -1c
.RI "uintptr_t \fBmmap_base\fP"
.br
.ti -1c
.RI "struct \fBmm_region\fP \fBmm_regions\fP [NREGIONS]"
.br
.ti -1c
.RI "elf_md * \fBelf_metadata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file thread\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
