.TH "tty" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tty
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBinitialized\fP"
.br
.ti -1c
.RI "int \fBpush_threshold\fP"
.br
.ti -1c
.RI "int \fBbuffer_index\fP"
.br
.ti -1c
.RI "pid_t \fBcontrolling_pgrp\fP"
.br
.ti -1c
.RI "void(* \fBprint_fn\fP )(const char *data, size_t len)"
.br
.ti -1c
.RI "char \fBbuffer\fP [1024]"
.br
.ti -1c
.RI "int \fBbuffer_mode\fP"
.br
.ti -1c
.RI "int \fBecho\fP"
.br
.ti -1c
.RI "struct \fBringbuf\fP \fBring\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file tty\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
