.TH "typedesc" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typedesc
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBtype_kind\fP"
.br
.ti -1c
.RI "uint16_t \fBtype_info\fP"
.br
.ti -1c
.RI "char \fBtype_name\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file ubsan\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
