#pragma once
#ifndef SNX_SYSCALLS_H
#define SNX_SYSCALLS_H

/** @file
 * @brief Include systematicaly generated syscalls
 */

#include <basic.h>
#include <dirent.h>
#include <snx/cpu.h>
#include <snx/fs.h>
#include <snx/syscall.h>
#include <snx/thread.h>
#include <snx/trace.h>
#include <signal.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/utsname.h>
#include <sys/wait.h>
#include <syscall_types.h>

#include "autogenerated_syscalls.h"

#endif
