#pragma once
#ifndef SNX_SYSCALL_CONSTS_H
#define SNX_SYSCALL_CONSTS_H

/** @file syscall_consts.h
 * @brief Includes systematicaly generated syscall constants
 * 
 */

#include "autogenerated_syscall_consts.h"

#endif
