.TH "_FILE" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_FILE
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int \fBunget_char\fP"
.br
.ti -1c
.RI "int \fBeof\fP"
.br
.ti -1c
.RI "off_t \fBoffset\fP"
.br
.ti -1c
.RI "size_t \fBbuflen\fP"
.br
.ti -1c
.RI "int \fBbufmode\fP"
.br
.ti -1c
.RI "size_t \fBbufsiz\fP"
.br
.ti -1c
.RI "char \fBbuffer\fP [BUFSIZ]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file fstdio\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
