.TH "acpi_rsdt" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acpi_rsdt
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBacpi_header\fP \fBheader\fP"
.br
.ti -1c
.RI "uint32_t \fBtable_ptr\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file acpi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
