.TH "acpi_madt_lapic" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acpi_madt_lapic
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBprocessor_id\fP"
.br
.ti -1c
.RI "unsigned char \fBid\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file acpi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
