.TH "double_complex" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
double_complex
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double complex \fBz\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   double \fBreal\fP"
.br
.ti -1c
.RI "   double \fBimag\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file complex\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
