.TH "file" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum file_type \fBtype\fP"
.br
.ti -1c
.RI "enum file_flags \fBflags\fP"
.br
.ti -1c
.RI "enum file_mode \fBmode\fP"
.br
.ti -1c
.RI "atomic_int \fBrefcnt\fP"
.br
.ti -1c
.RI "int \fBsignal_eof\fP"
.br
.ti -1c
.RI "int \fBuid\fP"
.br
.ti -1c
.RI "int \fBgid\fP"
.br
.ti -1c
.RI "off_t \fBlen\fP"
.br
.ti -1c
.RI "struct \fBfile_ops\fP * \fBops\fP"
.br
.ti -1c
.RI "struct \fBwq\fP \fBreadq\fP"
.br
.ti -1c
.RI "struct \fBwq\fP \fBwriteq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file fs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
