.TH "Format_Info" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Format_Info
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBbytes\fP"
.br
.ti -1c
.RI "Format \fBformat\fP"
.br
.ti -1c
.RI "bool \fBis_signed\fP"
.br
.ti -1c
.RI "bool \fBalternate_format\fP"
.br
.ti -1c
.RI "bool \fBprint_plus\fP"
.br
.ti -1c
.RI "bool \fBleave_space\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "enum { \fBLEFT\fP, \fBRIGHT\fP }"
.br
.ti -1c
.RI "   size_t \fBlen\fP"
.br
.ti -1c
.RI "   enum Format_Info:: { \&.\&.\&. }  \fBdirection\fP"
.br
.ti -1c
.RI "   char \fBc\fP"
.br
.ti -1c
.RI "} \fBpad\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file stdio\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
