.TH "irq_handler" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irq_handler
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBlist_n\fP \fBnode\fP"
.br
.ti -1c
.RI "void(* \fBhandler_func\fP )(\fBinterrupt_frame\fP *, void *)"
.br
.ti -1c
.RI "void * \fBimpl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file irq\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
