.TH "mod" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mod
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "struct \fBmodinfo\fP * \fBmodinfo\fP"
.br
.ti -1c
.RI "elf_md * \fBmd\fP"
.br
.ti -1c
.RI "struct \fBlist\fP \fBdeps\fP"
.br
.ti -1c
.RI "int \fBrefcnt\fP"
.br
.ti -1c
.RI "\fBlist_node\fP \fBnode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file mod\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
