.TH "multiboot_color" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_color
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBred\fP"
.br
.ti -1c
.RI "uint8_t \fBgreen\fP"
.br
.ti -1c
.RI "uint8_t \fBblue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 174 of file multiboot2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
