.TH "multiboot_tag_mmap" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_mmap
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "uint32_t \fBentry_size\fP"
.br
.ti -1c
.RI "uint32_t \fBentry_version\fP"
.br
.ti -1c
.RI "\fBmultiboot_mmap_entry\fP \fBentries\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 227 of file multiboot2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
