.TH "open_file" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
open_file
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBfile\fP * \fBfile\fP"
.br
.ti -1c
.RI "enum file_mode \fBmode\fP"
.br
.ti -1c
.RI "off_t \fBoff\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "off_t \fBbuffer_size\fP"
.br
.ti -1c
.RI "off_t \fBbuffer_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file fs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
