.TH "pipe_file" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pipe_file
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBfile\fP \fBfile\fP"
.br
.ti -1c
.RI "struct \fBringbuf\fP \fBring\fP"
.br
.ti -1c
.RI "atomic_int \fBnread\fP"
.br
.ti -1c
.RI "atomic_int \fBnwrite\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file pipe\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
