.TH "signal_context" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
signal_context
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "void * \fBsp\fP"
.br
.ti -1c
.RI "void * \fBbp\fP"
.br
.ti -1c
.RI "char * \fBstack\fP"
.br
.ti -1c
.RI "uintptr_t \fBip\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file signal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
