.TH "snx_dirent" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
snx_dirent
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum file_type \fBtype\fP"
.br
.ti -1c
.RI "enum file_mode \fBmode\fP"
.br
.ti -1c
.RI "char \fBname\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file dirent\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
