.TH "sockaddr_un" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sockaddr_un
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "sa_family_t \fBsun_family\fP"
.br
.ti -1c
.RI "char \fBsun_path\fP [108]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file un\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
