.TH "spalloc" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spalloc
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ssize_t \fBobject_size\fP"
.br
.ti -1c
.RI "const char * \fBtype_name\fP"
.br
.ti -1c
.RI "void * \fBregion\fP"
.br
.ti -1c
.RI "void * \fBfirst_free\fP"
.br
.ti -1c
.RI "void * \fBbump_free\fP"
.br
.ti -1c
.RI "ssize_t \fBcount\fP"
.br
.ti -1c
.RI "ssize_t \fBcapacity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file spalloc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
