.TH "stat" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stat
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "dev_t \fBst_dev\fP"
.br
.ti -1c
.RI "ino_t \fBst_ino\fP"
.br
.ti -1c
.RI "mode_t \fBst_mode\fP"
.br
.ti -1c
.RI "nlink_t \fBst_nlink\fP"
.br
.ti -1c
.RI "uid_t \fBst_uid\fP"
.br
.ti -1c
.RI "gid_t \fBst_gid\fP"
.br
.ti -1c
.RI "dev_t \fBst_rdev\fP"
.br
.ti -1c
.RI "off_t \fBst_size\fP"
.br
.ti -1c
.RI "blksize_t \fBst_blksize\fP"
.br
.ti -1c
.RI "blkcnt_t \fBst_blocks\fP"
.br
.ti -1c
.RI "time_t \fBst_atime\fP"
.br
.ti -1c
.RI "time_t \fBst_mtime\fP"
.br
.ti -1c
.RI "time_t \fBst_ctime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file stat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
