.TH "timeval" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timeval
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "time_t \fBtv_sec\fP"
.br
.ti -1c
.RI "suseconds_t \fBtv_usec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file time\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
