.TH "timer_event" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timer_event
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBat\fP"
.br
.ti -1c
.RI "enum timer_flags \fBflags\fP"
.br
.ti -1c
.RI "void(* \fBfn\fP )(void *)"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "const char * \fBfn_name\fP"
.br
.ti -1c
.RI "\fBlist_node\fP \fBnode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file timer\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
