.TH "tm" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tm
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtm_sec\fP"
.br
.ti -1c
.RI "int \fBtm_min\fP"
.br
.ti -1c
.RI "int \fBtm_hour\fP"
.br
.ti -1c
.RI "int \fBtm_mday\fP"
.br
.ti -1c
.RI "int \fBtm_mon\fP"
.br
.ti -1c
.RI "int \fBtm_year\fP"
.br
.ti -1c
.RI "int \fBtm_wday\fP"
.br
.ti -1c
.RI "int \fBtm_yday\fP"
.br
.ti -1c
.RI "int \fBtm_isdst\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file time\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
