.TH "ubsan_invalid_value_info" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ubsan_invalid_value_info
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBsource_location\fP \fBloc\fP"
.br
.ti -1c
.RI "struct \fBtypedesc\fP * \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file ubsan\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
