.TH "utsname" 3 "Sat Jul 24 2021" "SynnixOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utsname
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBsysname\fP [UNAME_STR_LEN]"
.br
.ti -1c
.RI "char \fBnodename\fP [UNAME_STR_LEN]"
.br
.ti -1c
.RI "char \fBrelease\fP [UNAME_STR_LEN]"
.br
.ti -1c
.RI "char \fBversion\fP [UNAME_STR_LEN]"
.br
.ti -1c
.RI "char \fBmachine\fP [UNAME_STR_LEN]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file utsname\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SynnixOS from the source code\&.
