
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Install Cross Compiler Dependencies
        run: sudo apt-get install -y libgmp-dev libmpfr-dev libmpc-dev
        
      - name: Build Cross Compiler
        run: ./scripts/build_toolchain.bash
      
      - name: Initial Build
        run: |
          ./scripts/generate_makefile.rb
          make

      - name: Build Ports
        run: |
          cd external
          ./make.bash
          cd -
      
      - name: Final Build
        run: |
          make
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: SynnixOS.iso
          path: ./synnixos.iso
          error: "Failed to upload ISO"
