
name: Build

on:
  schedule:
    - cron:  '30 10 * * *'



  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Install Cross Compiler Dependencies
        run: sudo apt-get install -y libgmp-dev libmpfr-dev libmpc-dev nasm grub-pc-bin xorriso mtools
        
      #- name: Build Cross Compiler
      #  run: ./scripts/build_toolchain.bash
      
      - name: Initial Build
        run: |
          ./scripts/generate_makefile.rb
          make

      - name: Build Ports
        run: |
          cd external
          ./make.bash
          cd -
      
      - name: Final Build
        run: |
          make
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: SynnixOS.iso
          path: ./synnixos.iso
          
      - name: Cache Cross Compiler
        uses: actions/cache@v2.1.6
        with:
          path: ~/.local/bin/
          
          key: ${{ runner.os }}-toolchain
