name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Obtaining Dependencies
        run: sudo apt-get install doxygen

      - name: Building Doxygen
        run: |
          cd docs
          doxygen
